# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(blank=True, null=True)),
                ('subscription_link', models.TextField(blank=True, null=True)),
                ('google_play_link', models.TextField(blank=True, null=True)),
                ('ios_appstore_link', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
