# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 21:43
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data_processor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedescription',
            name='viewing_windows',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
