# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processor', '0002_servicedescription_viewing_windows'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedescription',
            name='slug',
            field=models.TextField(blank=True, null=True),
        ),
    ]
