# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processor', '0003_servicedescription_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedescription',
            name='tooltip_tile_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
