# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data_processor', '0004_servicedescription_tooltip_tile_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('guidebox_data', jsonfield.fields.JSONField(blank=True, null=True)),
                ('modified', models.DateTimeField()),
                ('on_netflix', models.BooleanField()),
                ('channels_last_checked', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'server_content',
            },
        ),
        migrations.AlterField(
            model_name='servicedescription',
            name='viewing_windows',
            field=models.TextField(blank=True, null=True),
        ),
    ]
