# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data_processor', '0005_auto_20160629_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('guidebox_data', jsonfield.fields.JSONField(blank=True, null=True)),
                ('is_on_sling', models.BooleanField(default=False)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'server_channel',
                'managed': False,
            },
        ),
    ]
