# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processor', '0006_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewingServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('windows', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('ppv', models.BooleanField(default=False)),
            ],
        ),
    ]
