# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processor', '0008_auto_20160714_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewingservices',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
