# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processor', '0010_moduledescriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduledescriptions',
            name='img',
            field=models.TextField(blank=True, null=True),
        ),
    ]
