# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processor', '0011_moduledescriptions_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduledescriptions',
            name='level_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
