# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processor', '0012_moduledescriptions_level_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduledescriptions',
            name='affiliate_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
