# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 18:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data_processor', '0014_sports'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('name', models.TextField()),
                ('json_data', jsonfield.fields.JSONField(default='')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2016, 8, 8, 18, 32, 29, 70941, tzinfo=utc))),
            ],
        ),
        migrations.DeleteModel(
            name='Sports',
        ),
    ]
