# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 21:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data_processor', '0016_auto_20160808_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sport',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='sport',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 8, 21, 22, 25, 679830, tzinfo=utc)),
        ),
    ]
