# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 02:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_processor', '0024_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='team_logo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='data_processor.Sport'),
        ),
    ]
