# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 20:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_processor', '0013_moduledescriptions_affiliate_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popularity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.1)),
                ('date_created', models.DateField(default=datetime.datetime(2016, 8, 4, 20, 36, 53, 900728))),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_processor.Content')),
            ],
        ),
    ]
