# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 15:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('popularity', '0008_auto_20160809_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularity',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 9, 15, 28, 56, 928690, tzinfo=utc)),
        ),
    ]
