# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popularity', '0010_auto_20160809_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularity',
            name='curr_pop_score',
            field=models.FloatField(default=0.1),
        ),
    ]
