# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popularity', '0011_popularity_curr_pop_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popularity',
            name='curr_pop_score',
        ),
    ]
