# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-01 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data_processor', '0027_auto_20160821_0620'),
        ('popularity', '0012_remove_popularity_curr_pop_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='TMDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', jsonfield.fields.JSONField(blank=True, null=True)),
                ('date_created', models.DateTimeField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_processor.Content')),
            ],
            options={
                'get_latest_by': 'date_created',
            },
        ),
    ]
